version: '3.4'

services:
  TestTask:
    image: ${DOCKER_REGISTRY-}TestTask
    ports:
        - "8080:80"  
    build:
      context: .
      dockerfile: TestTAP-master/TestTAPTestTAP/Dockerfile
  postman_checks:
    image: postman/newman
    command:
        run https://www.getpostman.com/collections/1c53a8e4db4b97e734ca
        --reporters="junit,cli" --reporter-junit-export="newman-report.xml"
    volumes:
        - ./postman:/etc/newman