version: '3.4'

services:
  postman_checks:
    container_name: postman
    image: postman/newman
    depends_on:
     - apitestingproject
    command:
        run -v ~/postman:/etc/newman testtap.postman_collection.json \
        -e testtap.postman_environment.json \
        --reporters="junit,cli" --reporter-junit-export="newman-report.xml" \
        --suppress-exit-code
    volumes:
        - ./postman:/etc/newman

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    restart: unless-stopped
    depends_on:
     - apitestingproject