version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile

  postman_checks:
    image: postman/newman
    depends_on:
      - testtap
    command:
        run https://www.getpostman.com/collections/777348f8eb4d715d6b10
        --reporters="junit,cli" --reporter-junit-export="newman-report.xml"
    volumes:
        - ./postman:/etc/newman

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    restart: unless-stopped