version: '3.4'

services:
  postman_checks:
    image: postman/newman
    container_name: athlant_postman_container
    depends_on:
     - testtap
    command:
        run https://www.getpostman.com/collections/fa64f6a750163eae464a
        --reporters="junit,cli" --reporter-junit-export="newman-report.xml" -x
    volumes:
        - ./postman:/etc/newman

  postgres:
    image: postgres
    container_name: athlant_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    restart: unless-stopped
    depends_on:
      - testtap