version: '3.4'
# Swap with line 17 before final launch
# run testtap.postman_collection.json -e testtap.postman_environment.json

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ./Dockerfile

  postman_checks:
    image: postman/newman
    depends_on:
     - apitestingproject
    command:
        run postman_collection.json
        --reporters="junit,cli" --reporter-junit-export="newman-report.xml"
    volumes:
        - ./postman:/etc/newman

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    restart: unless-stopped
    depends_on:
     - apitestingproject